# Generated by Django 5.0 on 2023-12-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('moneda_from', models.CharField(max_length=100)),
                ('cantidad_from', models.FloatField()),
                ('moneda_to', models.CharField(max_length=100)),
                ('cantidad_to', models.FloatField()),
            ],
        ),
    ]
